apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: lesson
        image: hipython:latest
        env:
          - name: APP_VERSION
            value: "3"
        imagePullPolicy: Never
        ports:
        - containerPort: 80
      # Добавьте другие настройки, такие как ресурсы, переменные окружения и т. д., если необходимо
